name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.8-buster'
          - '5.10-buster'
          - '5.16-buster'
          - 'latest'
          - 'threaded'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install deb packages
        run: apt-get -qq update && apt-get -qq install -y unzip
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl -fsSL --compressed https://git.io/cpm | perl - install -g --with-configure --with-develop --with-recommends --show-build-log-on-failure
      - name: Run Tests
        run: prove -l t xt
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl -fsSL https://git.io/cpm | perl - install -g --with-develop --with-recommends --show-build-log-on-failure
      - name: Run Tests
        run: prove -lr t xt
